### ISSUE TITLE
Investigate - Node Server Hosting Options or Serverless

### ISSUE THREAD

**Issue by majdbrayhaus** [majdbrayhaus/brayhaus#16]
Investigate different hosting options for our node server and consider serverless options as well

**Comment by Quinten97** [comment]
**Options for server hosting**

### Server:

Some options we may have during prototyping.

1. [Glitch](https://glitch.com/)

- Projects sleep after 5 minutes if not used and are automatically stopped after 12 hours. They wake when receiving another HTTP request.
- 200MB disk space limit and 512MB assets storage space.
- 512MB RAM
- Limited to 4,000 requests per hour.

2. [Heroku](https://www.heroku.com/pricing)

- Sleeps after 30 mins of inactivity, otherwise always on depending on your remaining monthly free dyno hours.
- 512MB RAM
- 550-1,000 dyno hours per month
- Deploy with Git and Docker
- Custom domains
- Container orchestration
- Automatic OS patching

3. [AWS EC2 Free tier](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all)

-  750 hours of Linux and Windows t2.micro instances each month for the first year
- 5GB Storage
- lots of other free products such as DB, analytics, mobile


### Serverless

1. [Vercel](https://vercel.com/pricing)

- 100GB Bandwidth
- 100GB Hours
- Serverless Function Execution Timeout 5 seconds
- Unlimited Serverless Function Invocations

2. [Serverless](https://www.serverless.com/pricing)

- Free Monitoring Transactions 100,000/mo
- Unlimited Secrets

**Comment by majdbrayhaus** [comment]
@Quinten97 Netlify has some serverless hosting options, can we look into the pricing?

**Comment by Quinten97** [comment]
Yes can deff check that out

**Comment by Quinten97** [comment]
## Netlify Serverless Option

Here is the [pricing](https://www.netlify.com/pricing/) for Netlify as well as a quick overview into how their [serverless service](https://www.netlify.com/products/functions/) works.
 
Netlify allows you to upload a determined amount of functions and it will integrate them into their API. the coolest part is that they will create the endpoints for your application automatically.

- 125k functions per month are free then it is 25$ once exceeded 

there is a lot on the pricing page to take into consideration, they offer a ton of free services but scaling does look somewhat limited.
